# Generated by Django 5.1.7 on 2025-03-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_desc', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('item_image', models.ImageField(default='https://www.freepik.com/free-vector/loading-circles-blue-gradient_51017986.htm#fromView=keyword&page=1&position=1&uuid=a34d71ed-314b-4842-9d5f-c13fff321ba3&query=Loading+Png', upload_to='')),
            ],
        ),
    ]
